// Generated by CoffeeScript 1.7.1
(function() {
  window.setCookie = function(name, value) {
    return document.cookie = name + "=" + value;
  };

  window.getCookie = function(name) {
    var end, start, val;
    if (document.cookie.indexOf(name + "=") === -1) {
      return void 0;
    }
    start = void 0;
    end = void 0;
    if (document.cookie.length > 0) {
      start = document.cookie.indexOf(name + "=");
    }
    if (start !== -1) {
      start = start + name.length + 1;
      end = document.cookie.indexOf(";", start);
      if (end === -1) {
        end = document.cookie.length;
      }
      val = unescape(document.cookie.substring(start, end));
      if (val === "true") {
        val = true;
      }
      if (val === "false") {
        val = false;
      }
      return val;
    }
    return void 0;
  };

  window.clearCookie = function(key) {
    return document.cookie = "" + key + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
  };

  window.clearCookies = function() {
    var cookie, cookies, key, pos, _i, _len, _results;
    cookies = document.cookie.split(";");
    _results = [];
    for (_i = 0, _len = cookies.length; _i < _len; _i++) {
      cookie = cookies[_i];
      pos = cookie.indexOf("=");
      key = pos > -1 ? cookie.substr(0, pos) : cookie;
      _results.push(clearCookie(key));
    }
    return _results;
  };

  window.getQuery = function(name) {
    var regex, results;
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    regex = new RegExp("[\\?&]" + name + "=([^&#]*)");
    results = regex.exec(location.search);
    return (results == null ? void 0 : decodeURIComponent(results[1].replace(/\+/g, " ")));
  };

  window.searchify = function(obj) {
    var a, key, value;
    a = [];
    for (key in obj) {
      key = encodeURIComponent(key);
      value = encodeURIComponent(obj[key]);
      a.push("" + key + "=" + value);
    }
    return a.join("&");
  };

}).call(this);
