/**
 * Created by roi.levy on 10/5/14.
 */
'use strict';
function creativeModels(){

  var imageAsset = {
      "type": "Asset",
      "id": "",
      "clientRefId": null,
      "assetId": 0,
      "parentAssetId": 0,
      "parentSourceSystem": null,
      "assetType": "source",
      "mediaType": "IMAGE",
      "mimeType": null,
      "storagePath": null,
      "publishHostName": "http://images.qa.videofusion.com/",
      "publishPath": "d7627c76-c6ca-4204-b818-09ee33f053a8.jpg",
      "fileName": "",
      "status": "Available",
      "mpsVariantId": null,
      "mpsJobId": null,
      "createUserId": null,
      "modifyUserId": null,
      "createDateTime": 0,
      "modifyDateTime": null,
      "ingestDateTime": 0,
      "assetData": null,
      "currentVersion": true,
      "versionNumber": 1,
      "previousVersionAssetID": null,
      "assetCode": "",
      "codeType": null,
      "title": "",
      "metaSchemaId": 572854,
      "sourceSystemAssetId": 71377,
      "sourceSystem": "mio",
      "businessMetadata": {
        "audioBalistic": "",
        "userField4Label": "",
        "campaignId": "",
        "failureSummary": "",
        "clearanceProvider": "",
        "dgID": "",
        "brandId": "",
        "corporation": "",
        "assetSegments": "",
        "userField1": "",
        "userField5": "",
        "userField4": "",
        "userField3": "",
        "qualityControlSummary": "",
        "productionCompany": "",
        "effects": "",
        "poNumber": "",
        "destinationFolder": "",
        "userField3Label": "",
        "director": "",
        "jobNumber": "",
        "estimateNumber": "",
        "editor": "",
        "afd": "",
        "sound": "",
        "destinationLocalCodes": "",
        "advertiserId": "",
        "campaignName": "",
        "agencyAccountManager": "",
        "adFormat": "",
        "voiceArtist": "",
        "userField2Label": "",
        "audioLevelMaximumPermitted": "",
        "userField5Label": "",
        "userFieldArray": "",
        "userField1Label": "",
        "mediaAgency": "",
        "camera": "",
        "audioSetup": "",
        "titleSafe": "",
        "agency": "",
        "agencyPlanner": "",
        "product": "",
        "dimension": "",
        "audioScale": "",
        "profileID": "",
        "captionTypeCode": "",
        "creativeDirector": "",
        "brand": "",
        "displayName": "",
        "advertiser": "",
        "audioLoudnessLtandard": "",
        "clearanceState": "false"
      },
      "formatContext": {
        "audioStreamCount": 0,
        "bitRate": null,
        "decodingFailed": null,
        "duration": 0,
        "fileSize": 0,
        "format": "JPEG",
        "streamCount": null,
        "videoStreamCount": null
      },
      "audioStreamContext": null,
      "videoStreamContext": null,
      "swfContext": null,
      "extendedAdProperties": null,
      "imageContext": {
        "width": 0,
        "height": 0,
        "dataPrecision": "24",
        "compressionType": "JPEG",
        "extendedProperties": null
      },
      "thumbnails": [
        {
          "id": 0,
          "width": 0,
          "height": 0,
          "master": true,
          "name": "",
          "imageFormat": "JPEG",
          "url": ""
        }
      ],
      "relatedProxies": null,
      "width": 0,
      "height": 0,
      "archiveManifest": []
  }

  var flashAsset = {
    "type": "Asset",
    "id": "",
    "clientRefId": null,
    "assetId": 0,
    "parentAssetId": null,
    "parentSourceSystem": null,
    "assetType": "source",
    "mediaType": "FLASH",
    "mimeType": "application/x-shockwave-flash",
    "storagePath": "ftp://MioCDN:z9CimQG0O6@videof.upload.akamai.com/256931/m5qaimages/300x250_dbanner_1Q8IUX3LWQV.swf",
    "publishHostName": "http://images.qa.videofusion.com/",
    "publishPath": "300x250_dbanner_1Q8IUX3LWQV.swf",
    "fileName": "",
    "status": "Available",
    "mpsVariantId": null,
    "mpsJobId": 1073746842,
    "createUserId": null,
    "modifyUserId": null,
    "createDateTime": 0,
    "modifyDateTime": 0,
    "ingestDateTime": 0,
    "assetData": null,
    "currentVersion": true,
    "versionNumber": 1,
    "previousVersionAssetID": null,
    "assetCode": "",
    "codeType": null,
    "title": "",
    "metaSchemaId": null,
    "sourceSystemAssetId": null,
    "sourceSystem": "internal",
    "businessMetadata": {},
    "formatContext": {
      "audioStreamCount": null,
      "bitRate": null,
      "decodingFailed": null,
      "duration": null,
      "fileSize":0,
      "format": "swf",
      "streamCount": null,
      "videoStreamCount": null
    },
    "audioStreamContext": null,
    "videoStreamContext": null,
    "swfContext": {
      "height": 0,
      "isCompressed": true,
      "includeSV": true,
      "minVersion": 9,
      "ebVersion": 5072000,
      "ebDcVersion": -1,
      "isMobile": false,
      "isEBStdExist": false,
      "asversion": 3,
      "frameRate": 18,
      "backgroundColor": "#ffffffff",
      "includeDynamicCIName": false,
      "simpleExpX": 0,
      "simpleExpY": 0,
      "states": null,
      "dcforms": null,
      "dynamicContentData": null,
      "eyeblasterBlocks": null,
      "clickTags": null,
      "customInteractions": null,
      "width": 0
    },
    "extendedAdProperties": null,
    "imageContext": null,
    "thumbnails": [
      {
        "id": null,
        "width": null,
        "height": null,
        "master": null,
        "name": null,
        "imageFormat": null,
        "url": ""
      }
    ],
    "relatedProxies": null,
    "width": 0,
    "height": 0,
    "archiveManifest": []
  }

  var html5Asset = {
    "type": "AdAssetFolder",
    "id": "",
    "assetId": 0,
    "parentAssetId": null,
    "parentSourceSystem": null,
    "assetType": "source",
    "archiveManifest":[]
  }

    var archiveManifestObj =  {
        "id": "",
        "name": "",
        "path": "",
        "size": 0,
        "width": 0,
        "height": 0,
        "contentType": "IMAGE"
    }

  var ad = {
    "type":"",
    "id":"",
    "clientRefId":null,
    "name":"",
    "masterAdId":"",
    "changed":false,
    "adStatus":"AD_APPROVED",
    "adFormat":"",
    "accountId":"HRA1GI",
    "campaignId":"",
    "placementId":null,
    "createdBy":"HRA0OK",
    "createdOn":1412668171639,
    "lastUpdatedBy":"xxx",
    "lastUpdateOn":1412669837480,
    "mainClickthrough":{
      "type":"MainClickthrough",
      "id":"",
      "clientRefId":null,
      "url":"",
      "targetWindowType":"NEW",
      "showAddressBar":true,
      "showMenuBar":true,
      "closeAllAdParts":false
    },
    "adURLs":null,
    "pricingSize":0,
    "overallSize":0,
    "initialSize":0,
    "templateScriptName":"",
    "urlTokens":null,
    "minAudioVersion":0.0,
    "minFlashVersion":8.0,
    "adChoicesStatus":false,
    "adChoicesLocation":"TOP_RIGHT",
    "numberOfPlacementAds":0,
    "placementMV":false,
    "defaultImage":null,
    "defaultImageClickthrough":{
      "type":"MainClickthrough",
      "id":"",
      "clientRefId":null,
      "url":"",
      "targetWindowType":"NEW",
      "showAddressBar":true,
      "showMenuBar":true,
      "closeAllAdParts":false
    },
    "banner":null,
    "html5":null,
    "tooltip":""
  }

  return {
    imageAsset: imageAsset,
    flashAsset: flashAsset,
    html5Asset: html5Asset,
    archiveManifestObj: archiveManifestObj,
    ad: ad
  }

}
